### ISSUE TITLE
Neue Aktion anlegen: Rotation der Attached Elemente

### ISSUE THREAD

**Issue by A-V-Lorenz** [rhoentier/ss22_fp_mapc-group_5#16]
Action: rotate

Rotates the agent (and all attached things) 90 degrees in the given direction. For each attached thing, its final position after the rotation has to be free.

Parameter:
cw, ccw

Beispiel:
new Action("rotate", "cw");

**Comment by A-V-Lorenz** [comment]
Das issue ist nicht erfüllt.

Für das rotieren der Elemente muss zuerst die Abfrage des Rotationsziels erfolgen.
Erst wenn frei, darf rotiert werden.

**Comment by rhoentier** [comment]
Ah okay, das hab ich übersehen.
Wenn solche Abfragen mit in das Ticket sollen, dann würde ich Vorschlagen, dass wir die direkt mit reinschreiben :-)

Soll die Abfrage über unsere interne Map laufen, damit wir keinen Schritt brauchen, oder soll eine Abfrage an den Server geschickt werden?

**Comment by seblod90** [comment]
Ich würde das über die Map machen. Bei mehreren attached-Blocks kann es sein, dass man dann einige Felder prüfen muss.

Ich schaffe das leider nicht mehr bis heute Abend, würde das aber dann zeitnah übernehmen. Wenn die Funktion bereits irgendwo benötigt wird, bitte nochmal melden. (nicht dass hierdurch was anderes still steht)

**Comment by rhoentier** [comment]
Ich hab das grade gemacht. Aber @seblod90, schau am besten nochmal drüber, ob ich deine Methoden alle richtig interpretiert habe

**Comment by seblod90** [comment]
Sieht gut aus. Danke nochmal fürs übernehmen ;) 

- Später wird es vielleicht erforderlich, mehr als ein anghängtes Objekt zu drehen, d.h. das müssen wir dann vielleicht nochmal erweitern. Für jetzt sollte das aber erstmal ausreichen.
- Vielleicht macht es Sinn, dem MapTile eine Eigenschaft "walkable" (o.ä.) zu geben. Da könnte man sich das mit den Abfragen etwas einfacher machen. obstacle, block, entity und dispenser wären dann nicht walkable, alle anderen schon.

Sollen wir solche Ideen bzw. ToDos für später auch als Issues aufnehmen und mit einem Tag versehen?

**Comment by seblod90** [comment]
> Vielleicht macht es Sinn, dem MapTile eine Eigenschaft "walkable" (o.ä.) zu geben. Da könnte man sich das mit den Abfragen etwas einfacher machen. obstacle, block, entity und dispenser wären dann nicht walkable, alle anderen schon.

erledigt. Macht den Code etwas einfacher.
