### ISSUE TITLE
Erkundung der Karte zu beginn des Spiels

### ISSUE THREAD

**Issue by rhoentier** [rhoentier/ss22_fp_mapc-group_5#20]
Der NextAgent soll eine Methode bekommen, die die Erkundung der Karte implementiert.

Der Agent läuft zum Beginn des Spiels in einer einfachen, aber klugen Art über die Karte um ein möglichst großes Gebiet zu erkunden. Bisher ist noch keine Information der Karte vorhanden. Es geht lediglich darum erstmal eine Repräsentation der Karte aufzubauen
Zum Beginn legen wir vor allem Wert auf eine einfache Implementierung, die wir mit der Zeit überarbeiten können.

**Comment by MiniMiri** [comment]
https://github.com/kevinsheehan/jps

**Comment by MiniMiri** [comment]
Eine einfache Erkundung für die Karte wird mit einer Spirale gemacht. Hier kann auch die Schrittweite angegeben, mit dem der Agent im Kreis läuft.
>>NextSpiralPath
