### ISSUE TITLE
Wegfindealgorithmus implementieren

### ISSUE THREAD

**Issue by rhoentier** [rhoentier/ss22_fp_mapc-group_5#26]
Agenten müssen den kürzesten Weg zu Objekten oder Bereichen finden.

 - [x] Zuerst sollte eine Art Interface gebaut werden, damit den Wegfindealgorithmus austauschen können.
 - [ ] Anschließend sollte ein einfacher Wegfindealgorithmus implementiert werden, der den direkten Weg auf der leeren Map findet
 - [ ] Abschließend sollte ein komplexerer Algorithmus (A* oder JPS) implementiert werden, der auf einer nicht leeren Map den kürzesten Weg findet.

**Comment by MiniMiri** [comment]
https://blog.viking-studios.net/wp-content/uploads/2013/04/Pathfinding-Algorithmen-in-verschiedenen-Spielegenres.pdf

https://www.uni-kassel.de/eecs/index.php?eID=dumpFile&t=f&f=1581&token=8ba34c1c49d2f21b0d18c36a249dff0075988586

**Comment by MiniMiri** [comment]
Glaub das wurd schon von Alex gelöst.
