### ISSUE TITLE
Kommunikation zwischen Agenten 

### ISSUE THREAD

**Issue by rhoentier** [rhoentier/ss22_fp_mapc-group_5#27]
Für die Funktion müssen sich die Agenten zuerst am Mail system anmelden.

- [x] Agenten beim MailService anmelden
- [x] Kommunikation über sendMessage( ) und handleMessage( ) implementieren
- [x] Kommunikation über broadcast( ) implementieren

**Comment by A-V-Lorenz** [comment]
Alle Punkte funktionieren bereits out of the Box
