### ISSUE TITLE
Turnier vorbereitungen treffen

### ISSUE THREAD

**Issue by rhoentier** [rhoentier/ss22_fp_mapc-group_5#39]
Es müssen alle Vorbereitungen für das Turnier getroffen werden. Es soll also die Config geändert werden, damit die Agenten mit einem externen Server kommunzieren können.
Falls noch weitere Vorbereitungen getroffen werden müssen, dann sollen diese gefunden und geändert werden. Dabei sind nur die Rahmenbedingungen und kein aktives Verhalten der Agenten gemeint.

- [ ] Turnier config erstellen, die bei Bedarf eingebunden werden kann
- [ ] Weitere Punkte für die Turniervorbereitung suchen und ggf. vorbereiten

**Comment by A-V-Lorenz** [comment]
Ich habe am Samstag Miri beim Einrichten vom Server geholfen. Der NextAgent lief bereits auf dem Uniserver ;)

Falls ihr die Config Files haben wollt, füge ich das zum develop Branch hinzu.

**Comment by rhoentier** [comment]
Sehr gerne!
Dann würde ich wieder ein kurzes Script schreiben, dass die richtige Agent config lädt

**Comment by A-V-Lorenz** [comment]
Die Config und auch der Startskript ist online. Wir müssen nur vorab noch 1mal den Agenten mit dem Uniserver verbinden für alle Fälle.
