### ISSUE TITLE
NextMap: attachedElements beim Mapping nicht berücksichtigen

### ISSUE THREAD

**Issue by seblod90** [rhoentier/ss22_fp_mapc-group_5#44]
Die "eigenen" attachedElements beim Mapping nicht berücksichtigen. Ich denke dass es Sinn macht, dass diese eine reine Eigenschaft des Agents sind. Andernfalls würde in der Karte eine "Spur" der Elemente erzeugt werden. 
 
Das könnte z.B. ein Problem bei der Rotation geben: 
- Agent hat in Richtungen N und E je ein Element und möchte CW rotieren
- Abfrage scheitert vermutlich, da die neue Position von N belegt ist (da wo E aktuell ist). 
- E dreht sich aber auch weiter und wäre eigentlich nicht belegt. 

Generell macht es vielleicht Sinn, dass die Karte überwiegend statische / gering dynamische Elemente enthält (Obstacles, Dispenser, Goal-/Role-Zones). Die sehr dynamischen Elemente (attached Elements, eigene Position, Position der anderen Agenten) eher nicht.  

Gerne offen zur Diskussion!

**Comment by rhoentier** [comment]
Ja finde ich richtig!
Willst du das direkt umsetzten?

**Comment by seblod90** [comment]
done
