### ISSUE TITLE
Die Agenten versuchen abgelaufene Tasks abzugeben.  

### ISSUE THREAD

**Issue by A-V-Lorenz** [rhoentier/ss22_fp_mapc-group_5#80]
Beobachtung:
Der Agent steht in der Rolezone, und versucht eine Aufgabe abzugeben, die abgelaufen ist.
Dabei ist eine neue, identische Aufgabe vorhanden.

----

Vorschlag, kurz vor der Abgabe prüfen, ob die ausgewählte Task noch relevant ist.

**Comment by MiniMiri** [comment]
Steffen muss sich das noch anschauen :)

**Comment by MiniMiri** [comment]
Ist erledigt. Abgelaufene Tasks werden verworfen
